//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/0. Scripts/Players/PlayerBase/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Land"",
            ""id"": ""2ec83ddd-1971-45c7-be31-ba7812817760"",
            ""actions"": [
                {
                    ""name"": ""move"",
                    ""type"": ""Value"",
                    ""id"": ""11f470e6-6814-4e0c-a625-905e9b8c4ccc"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""jump"",
                    ""type"": ""Button"",
                    ""id"": ""bdd6a7b1-866d-4611-80a0-db6233e4ec5f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""action"",
                    ""type"": ""Button"",
                    ""id"": ""25547b42-f469-4257-8679-dd41b4193edd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""switchChar1"",
                    ""type"": ""Button"",
                    ""id"": ""176c409c-8292-44be-a46b-421898b0393b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""switchChar2"",
                    ""type"": ""Button"",
                    ""id"": ""edc3510c-bbff-42a7-851d-7c54582fbeca"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""switchChar3"",
                    ""type"": ""Button"",
                    ""id"": ""89582eb9-dc09-4048-aa98-b5f4034b844b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""switchChar4"",
                    ""type"": ""Button"",
                    ""id"": ""a20dcdf3-1c2e-443b-b842-7408a20df6aa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""pausing"",
                    ""type"": ""Button"",
                    ""id"": ""7fe495e1-13cb-45e6-8e18-d0865ae063e3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""12d9a5ca-ae70-4a06-8c9b-fd961ed2e265"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""923b61aa-4d3d-4133-bd93-196ef7e5cd52"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9bc3f4c8-ba02-4d7b-81ab-b55cd67d61e0"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b630914b-28c5-4d2c-8590-82dbfc1d5fdb"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""8301afb9-ee61-44d7-a641-b1dc0508aa6b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""63422ae7-fbc2-4f32-8104-e91aff6c41a2"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Arrow Kyes"",
                    ""id"": ""2570e818-b6a6-4ea7-b408-11d7fb66f49f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e6e51eaa-ee15-43a9-a4c9-9532c45f57c3"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""71a42958-cd3b-4728-88f7-9d15f0d584b0"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a0bb8d1d-bb16-45d8-a4ae-2bb0323dbc78"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4e2bf674-a810-4387-898e-79a0c5a389a1"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f8ed822a-4df9-4eff-b48e-b91fdd755432"",
                    ""path"": ""<Joystick>/stick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""11c05a2b-fa5d-4ebb-96fc-53af9327cee9"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""af7e3e46-ac7e-48e9-bca6-6e8bd9a94cd4"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""a791c719-ecf7-4d3f-a441-f7c4e4cbfc00"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Two Modifiers"",
                    ""id"": ""9f223b6a-bbe6-4a0d-a242-b94eeb72313f"",
                    ""path"": ""TwoModifiers"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier1"",
                    ""id"": ""114a98c6-c265-4583-923f-886030c3958d"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""modifier2"",
                    ""id"": ""80bf8b6c-592f-404e-9c15-df317dcd9ecd"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""57c6abd3-983a-46ba-95bd-0f75315127e0"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""408a8b29-8c89-40aa-bfdd-468053d7994d"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fc2b9c97-bad4-41ea-a458-b6ca67cc9af7"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42130f0c-ab40-4d5a-a73d-b000ac928051"",
                    ""path"": ""<Keyboard>/leftAlt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""130c6f11-4b0c-4427-a8ef-830f9f970fde"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""switchChar1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05bf31d0-da36-4a22-b1c8-e0b1863e391b"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""switchChar2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""38cfed98-19cd-4723-b627-b205c3687c95"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""switchChar3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c97ef04-134e-4b6e-9dd0-f1ad596949f2"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""switchChar4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c82686aa-b9d8-4f97-81c4-42c12805dfbc"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""pausing"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Land
        m_Land = asset.FindActionMap("Land", throwIfNotFound: true);
        m_Land_move = m_Land.FindAction("move", throwIfNotFound: true);
        m_Land_jump = m_Land.FindAction("jump", throwIfNotFound: true);
        m_Land_action = m_Land.FindAction("action", throwIfNotFound: true);
        m_Land_switchChar1 = m_Land.FindAction("switchChar1", throwIfNotFound: true);
        m_Land_switchChar2 = m_Land.FindAction("switchChar2", throwIfNotFound: true);
        m_Land_switchChar3 = m_Land.FindAction("switchChar3", throwIfNotFound: true);
        m_Land_switchChar4 = m_Land.FindAction("switchChar4", throwIfNotFound: true);
        m_Land_pausing = m_Land.FindAction("pausing", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Land
    private readonly InputActionMap m_Land;
    private List<ILandActions> m_LandActionsCallbackInterfaces = new List<ILandActions>();
    private readonly InputAction m_Land_move;
    private readonly InputAction m_Land_jump;
    private readonly InputAction m_Land_action;
    private readonly InputAction m_Land_switchChar1;
    private readonly InputAction m_Land_switchChar2;
    private readonly InputAction m_Land_switchChar3;
    private readonly InputAction m_Land_switchChar4;
    private readonly InputAction m_Land_pausing;
    public struct LandActions
    {
        private @PlayerControls m_Wrapper;
        public LandActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @move => m_Wrapper.m_Land_move;
        public InputAction @jump => m_Wrapper.m_Land_jump;
        public InputAction @action => m_Wrapper.m_Land_action;
        public InputAction @switchChar1 => m_Wrapper.m_Land_switchChar1;
        public InputAction @switchChar2 => m_Wrapper.m_Land_switchChar2;
        public InputAction @switchChar3 => m_Wrapper.m_Land_switchChar3;
        public InputAction @switchChar4 => m_Wrapper.m_Land_switchChar4;
        public InputAction @pausing => m_Wrapper.m_Land_pausing;
        public InputActionMap Get() { return m_Wrapper.m_Land; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LandActions set) { return set.Get(); }
        public void AddCallbacks(ILandActions instance)
        {
            if (instance == null || m_Wrapper.m_LandActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_LandActionsCallbackInterfaces.Add(instance);
            @move.started += instance.OnMove;
            @move.performed += instance.OnMove;
            @move.canceled += instance.OnMove;
            @jump.started += instance.OnJump;
            @jump.performed += instance.OnJump;
            @jump.canceled += instance.OnJump;
            @action.started += instance.OnAction;
            @action.performed += instance.OnAction;
            @action.canceled += instance.OnAction;
            @switchChar1.started += instance.OnSwitchChar1;
            @switchChar1.performed += instance.OnSwitchChar1;
            @switchChar1.canceled += instance.OnSwitchChar1;
            @switchChar2.started += instance.OnSwitchChar2;
            @switchChar2.performed += instance.OnSwitchChar2;
            @switchChar2.canceled += instance.OnSwitchChar2;
            @switchChar3.started += instance.OnSwitchChar3;
            @switchChar3.performed += instance.OnSwitchChar3;
            @switchChar3.canceled += instance.OnSwitchChar3;
            @switchChar4.started += instance.OnSwitchChar4;
            @switchChar4.performed += instance.OnSwitchChar4;
            @switchChar4.canceled += instance.OnSwitchChar4;
            @pausing.started += instance.OnPausing;
            @pausing.performed += instance.OnPausing;
            @pausing.canceled += instance.OnPausing;
        }

        private void UnregisterCallbacks(ILandActions instance)
        {
            @move.started -= instance.OnMove;
            @move.performed -= instance.OnMove;
            @move.canceled -= instance.OnMove;
            @jump.started -= instance.OnJump;
            @jump.performed -= instance.OnJump;
            @jump.canceled -= instance.OnJump;
            @action.started -= instance.OnAction;
            @action.performed -= instance.OnAction;
            @action.canceled -= instance.OnAction;
            @switchChar1.started -= instance.OnSwitchChar1;
            @switchChar1.performed -= instance.OnSwitchChar1;
            @switchChar1.canceled -= instance.OnSwitchChar1;
            @switchChar2.started -= instance.OnSwitchChar2;
            @switchChar2.performed -= instance.OnSwitchChar2;
            @switchChar2.canceled -= instance.OnSwitchChar2;
            @switchChar3.started -= instance.OnSwitchChar3;
            @switchChar3.performed -= instance.OnSwitchChar3;
            @switchChar3.canceled -= instance.OnSwitchChar3;
            @switchChar4.started -= instance.OnSwitchChar4;
            @switchChar4.performed -= instance.OnSwitchChar4;
            @switchChar4.canceled -= instance.OnSwitchChar4;
            @pausing.started -= instance.OnPausing;
            @pausing.performed -= instance.OnPausing;
            @pausing.canceled -= instance.OnPausing;
        }

        public void RemoveCallbacks(ILandActions instance)
        {
            if (m_Wrapper.m_LandActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ILandActions instance)
        {
            foreach (var item in m_Wrapper.m_LandActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_LandActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public LandActions @Land => new LandActions(this);
    public interface ILandActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnAction(InputAction.CallbackContext context);
        void OnSwitchChar1(InputAction.CallbackContext context);
        void OnSwitchChar2(InputAction.CallbackContext context);
        void OnSwitchChar3(InputAction.CallbackContext context);
        void OnSwitchChar4(InputAction.CallbackContext context);
        void OnPausing(InputAction.CallbackContext context);
    }
}
